<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Teacher;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                'name' => 'Dr. Yudi Setiawan, S.T., M.Eng.',
                'role' => 'kaprodi',
                'title' => 'Kepala Program Studi Sistem Informasi',
                'expertise' => ['Software Engineering', 'AI'],
                'publications' => 45,
                'projects' => 12,
                'email' => 'yudi.setiawan@university.ac.id',
                'phone' => '+62 812-3456-7890',
                'linkedin' => 'https://linkedin.com/in/yudisetiawan',
                'google_scholar' => 'https://scholar.google.com/citations?user=abc123',
                'bio' => 'Lulusan Doktor bidang Software Engineering dengan spesialisasi Artificial Intelligence. Memiliki pengalaman penelitian lebih dari 15 tahun di bidang pengembangan sistem cerdas dan arsitektur perangkat lunak. Aktif membimbing mahasiswa dalam penelitian dan pengembangan aplikasi berbasis AI.',
                'gradient' => 'linear-gradient(135deg, #1a246a, #151945)',
                'icon' => 'fa-user-tie',
                'badge_color' => '#fbbf24',
                'order' => 1,
            ],
            [
                'name' => 'Niska Ramadhani, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Data Science', 'Machine Learning'],
                'publications' => 32,
                'projects' => 8,
                'email' => 'niska.ramadhani@university.ac.id',
                'phone' => '+62 813-4567-8901',
                'linkedin' => 'https://linkedin.com/in/niskaramadhani',
                'google_scholar' => 'https://scholar.google.com/citations?user=def456',
                'bio' => 'Pakar dalam bidang Data Science dan Machine Learning dengan fokus pada analisis data dan pengembangan model prediktif. Berpengalaman dalam mengelola proyek big data untuk berbagai industri.',
                'gradient' => 'linear-gradient(135deg, #f59e0b, #d97706)',
                'icon' => 'fa-user-graduate',
                'badge_color' => null,
                'order' => 2,
            ],
            [
                'name' => 'Aan Erlanshari, S.T., M.Eng.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Network Security', 'Cloud Computing'],
                'publications' => 28,
                'projects' => 10,
                'email' => 'aan.erlanshari@university.ac.id',
                'phone' => '+62 814-5678-9012',
                'linkedin' => 'https://linkedin.com/in/aanerlanshari',
                'google_scholar' => null,
                'bio' => 'Ahli keamanan jaringan dan cloud computing. Memiliki sertifikasi internasional di bidang cybersecurity dan berpengalaman dalam merancang infrastruktur cloud yang aman dan scalable.',
                'gradient' => 'linear-gradient(135deg, #1d4ed8, #151945)',
                'icon' => 'fa-user-cog',
                'badge_color' => null,
                'order' => 3,
            ],
            [
                'name' => 'Soni Ayi Purnama, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Database', 'Business Intelligence'],
                'publications' => 24,
                'projects' => 6,
                'email' => null,
                'phone' => '+62 815-6789-0123',
                'linkedin' => null,
                'google_scholar' => 'https://scholar.google.com/citations?user=ghi789',
                'bio' => 'Spesialis dalam perancangan dan optimasi database serta pengembangan sistem Business Intelligence untuk mendukung pengambilan keputusan strategis organisasi.',
                'gradient' => 'linear-gradient(135deg, #059669, #047857)',
                'icon' => 'fa-user-check',
                'badge_color' => null,
                'order' => 4,
            ],
            [
                'name' => 'Yusran Panca Putra, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Web Development', 'UI/UX'],
                'publications' => 20,
                'projects' => 14,
                'email' => 'yusran.putra@university.ac.id',
                'phone' => null,
                'linkedin' => 'https://linkedin.com/in/yusranpancaputra',
                'google_scholar' => null,
                'bio' => 'Praktisi dan pengajar di bidang Web Development dan UI/UX Design. Berfokus pada pengembangan aplikasi web modern dengan pengalaman pengguna yang optimal.',
                'gradient' => 'linear-gradient(135deg, #ef4444, #dc2626)',
                'icon' => 'fa-user-edit',
                'badge_color' => null,
                'order' => 5,
            ],
            [
                'name' => 'Julia Purnama Sari, S.T., M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Cyber Security', 'Blockchain'],
                'publications' => 18,
                'projects' => 9,
                'bio' => 'Peneliti cyber security dan blockchain technology. Aktif dalam pengembangan sistem keamanan informasi dan implementasi teknologi blockchain untuk berbagai aplikasi.',
                'gradient' => 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
                'icon' => 'fa-user-shield',
                'badge_color' => null,
                'order' => 6,
            ],
            [
                'name' => 'Ahmad Taufik, S.Kom., M.T.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Mobile Development', 'IoT'],
                'publications' => 16,
                'projects' => 11,
                'bio' => 'Pengembang aplikasi mobile dan sistem IoT. Berpengalaman dalam membangun aplikasi mobile cross-platform dan integrasi dengan perangkat IoT.',
                'gradient' => 'linear-gradient(135deg, #06b6d4, #0891b2)',
                'icon' => 'fa-user-code',
                'badge_color' => null,
                'order' => 7,
            ],
            [
                'name' => 'Rina Wati, S.Kom., M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Data Mining', 'Big Data'],
                'publications' => 22,
                'projects' => 7,
                'bio' => 'Spesialis Data Mining dan Big Data analytics. Fokus penelitian pada pengembangan algoritma data mining untuk mengekstraksi pola dan pengetahuan dari data berskala besar.',
                'gradient' => 'linear-gradient(135deg, #f97316, #ea580c)',
                'icon' => 'fa-user-tie',
                'badge_color' => null,
                'order' => 8,
            ],
            [
                'name' => 'Budi Santoso, S.Kom., M.T.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Game Development', 'Computer Graphics'],
                'publications' => 15,
                'projects' => 5,
                'bio' => 'Ahli pengembangan game dan computer graphics. Berpengalaman dalam merancang dan mengembangkan game edukatif serta aplikasi berbasis grafis 3D.',
                'gradient' => 'linear-gradient(135deg, #ec4899, #db2777)',
                'icon' => 'fa-user-astronaut',
                'badge_color' => null,
                'order' => 9,
            ],
            [
                'name' => 'Siti Nurhaliza, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['ERP Systems', 'Information Systems'],
                'publications' => 19,
                'projects' => 8,
                'bio' => 'Konsultan dan peneliti sistem ERP dan Information Systems. Memiliki pengalaman dalam implementasi dan customisasi sistem ERP untuk berbagai skala perusahaan.',
                'gradient' => 'linear-gradient(135deg, #14b8a6, #0d9488)',
                'icon' => 'fa-user-tag',
                'badge_color' => null,
                'order' => 10,
            ],
            [
                'name' => 'Eko Prasetyo, S.T., M.Eng.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['DevOps', 'System Administration'],
                'publications' => 21,
                'projects' => 9,
                'bio' => 'Praktisi DevOps dan System Administration dengan keahlian dalam automation, CI/CD, dan infrastructure as code. Berpengalaman mengelola sistem cloud-based infrastructure.',
                'gradient' => 'linear-gradient(135deg, #6366f1, #4f46e5)',
                'icon' => 'fa-user-secret',
                'badge_color' => null,
                'order' => 11,
            ],
            [
                'name' => 'Dewi Lestari, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['HCI', 'User Research'],
                'publications' => 17,
                'projects' => 6,
                'bio' => 'Peneliti Human-Computer Interaction dan User Experience. Fokus pada metodologi user research dan evaluasi usability untuk menghasilkan produk digital yang user-centered.',
                'gradient' => 'linear-gradient(135deg, #f43f5e, #e11d48)',
                'icon' => 'fa-user-friends',
                'badge_color' => null,
                'order' => 12,
            ],
            [
                'name' => 'Faisal Rahman, S.Kom., M.T.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['AR/VR', '3D Modeling'],
                'publications' => 14,
                'projects' => 7,
                'bio' => 'Pengembang aplikasi Augmented Reality dan Virtual Reality. Berpengalaman dalam pembuatan konten 3D dan implementasi teknologi immersive untuk pendidikan dan industri.',
                'gradient' => 'linear-gradient(135deg, #a855f7, #9333ea)',
                'icon' => 'fa-user-ninja',
                'badge_color' => null,
                'order' => 13,
            ],
            [
                'name' => 'Indah Permata, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Natural Language Processing', 'Text Mining'],
                'publications' => 26,
                'projects' => 10,
                'bio' => 'Ahli Natural Language Processing dan Text Mining. Penelitian fokus pada pengembangan sistem pemrosesan bahasa alami untuk analisis teks dan sentiment analysis.',
                'gradient' => 'linear-gradient(135deg, #84cc16, #65a30d)',
                'icon' => 'fa-user-graduate',
                'badge_color' => null,
                'order' => 14,
            ],
            [
                'name' => 'Hendra Wijaya, S.T., M.Eng.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Robotics', 'Embedded Systems'],
                'publications' => 23,
                'projects' => 12,
                'bio' => 'Peneliti robotika dan embedded systems. Berpengalaman dalam perancangan sistem robotik intelligent dan pengembangan aplikasi embedded untuk automation.',
                'gradient' => 'linear-gradient(135deg, #0ea5e9, #0284c7)',
                'icon' => 'fa-user-cog',
                'badge_color' => null,
                'order' => 15,
            ],
            [
                'name' => 'Mega Puspita, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Digital Marketing', 'E-Commerce'],
                'publications' => 13,
                'projects' => 8,
                'bio' => 'Praktisi Digital Marketing dan E-Commerce. Fokus pada strategi pemasaran digital, SEO/SEM, dan pengembangan platform e-commerce yang efektif.',
                'gradient' => 'linear-gradient(135deg, #f59e0b, #d97706)',
                'icon' => 'fa-user-tie',
                'badge_color' => null,
                'order' => 16,
            ],
            [
                'name' => 'Randi Kusuma, S.Kom., M.T.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Image Processing', 'Computer Vision'],
                'publications' => 25,
                'projects' => 11,
                'bio' => 'Peneliti Image Processing dan Computer Vision. Berpengalaman dalam pengembangan sistem pengenalan pola, object detection, dan image recognition menggunakan deep learning.',
                'gradient' => 'linear-gradient(135deg, #10b981, #059669)',
                'icon' => 'fa-user-check',
                'badge_color' => null,
                'order' => 17,
            ],
            [
                'name' => 'Putri Ayu, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Software Testing', 'Quality Assurance'],
                'publications' => 18,
                'projects' => 9,
                'bio' => 'Spesialis Software Testing dan Quality Assurance. Ahli dalam merancang test strategy, automation testing, dan memastikan kualitas software melalui comprehensive testing approach.',
                'gradient' => 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
                'icon' => 'fa-user-shield',
                'badge_color' => null,
                'order' => 18,
            ],
            [
                'name' => 'Dani Kurniawan, S.T., M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Information Security', 'Cryptography'],
                'publications' => 27,
                'projects' => 13,
                'bio' => 'Ahli Information Security dan Cryptography. Fokus penelitian pada pengembangan algoritma kriptografi, secure communication systems, dan data protection mechanisms.',
                'gradient' => 'linear-gradient(135deg, #1a246a, #151945)',
                'icon' => 'fa-user-secret',
                'badge_color' => null,
                'order' => 19,
            ],
            [
                'name' => 'Lisa Anggraini, M.Kom.',
                'role' => 'dosen',
                'title' => 'Dosen Sistem Informasi',
                'expertise' => ['Project Management', 'Agile Methodologies'],
                'publications' => 20,
                'projects' => 15,
                'bio' => 'Praktisi Project Management dengan sertifikasi PMP dan Scrum Master. Berpengalaman mengelola proyek IT skala besar menggunakan metodologi Agile dan Scrum.',
                'gradient' => 'linear-gradient(135deg, #f97316, #ea580c)',
                'icon' => 'fa-user-edit',
                'badge_color' => null,
                'order' => 20,
            ],
        ];

        foreach ($teachers as $teacher) {
            Teacher::updateOrCreate(
                ['name' => $teacher['name']],
                $teacher
            );
        }
    }
}
